[package]
name = "leftwm-config"
version = "0.1.0"
authors = ["BlackDragon2447 <blackdragon2447@e.email>"]
edition = "2021"
license = "MIT"
readme = "README.md"
#description = "A window manager for Adventurers"

[dependencies]
anyhow = {version="1.0.48", features=["backtrace"]}
clap = "3.2.19"
xdg = "2.2.0"
serde = { version = "1.0.104", features = ["derive", "rc"] }
ron = "0.8.0"
serde_json = "1.0.44"
log = "0.4.8"
git-version = "0.3.4"
thiserror = "1.0.30"

tuirealm = "1.8.0"
tui-realm-stdlib = "1.2.0"

crossterm = "0.25.0"
glob = "0.3.0"
toml = "0.5.9"
